name: ICUr
channels:
 - conda-forge
dependencies:
  - python=3.9
  - r-base=4.1
  - r-tidyverse
  - r-rstudio
  - pip
  - ipython
  - nbconvert
  - nbformat
  - jupyter
  - jupyterlab
  - pip:
    - black
    - pre-commit
